import SectionContainer from "@/components/SectionContainer";
import Head from "next/head";
import { NextPage } from "next/types";

const About: NextPage = () => {
    return (
        <SectionContainer>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <section>
                This is about me!
            </section>
        </SectionContainer>
    );
};

export default About;