import type { NextPage } from 'next';
import Head from 'next/head';
import Link from 'next/link';
import { getDatabase, getPostList } from '../lib/notion';

export const databaseId: string = process.env.NOTION_DATABASE_ID as string;

const Home: NextPage = ({ posts }: any) => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <ul>
        {
          posts.map((post: any) => {
            return (
              <Link href={`blog/${post.id}`}>
                <a> Read post →</a>
              </Link>
            )
          })
        }
      </ul>

    </div>
  );
};

export const getStaticProps = async () => {
  const database = await getDatabase(databaseId);
  const { posts } = getPostList(database);

  return {
    props: {
      posts: posts,
    },
    revalidate: 1,
  };
};

export default Home;
